---
#- name: Setup
#  hosts: all
#  roles:
#    - role: setup
#      become: true
#      tags: [ setup ]

- name: Setup Portainer
  hosts: all
  roles:
    - role: portainer
      vars:
        agent_only: false
