---
- name: Create Portainer Pod
  containers.podman.pod:
    name: podman
    publish:
      - 9443:9443

- name: Run Portainer
  containers.podman.podman_container:
    name: portainer
    image: portainer/portainer-ee
    restart_policy: always
    pod: podman
    volumes:
      - data:/data

- name: Run Portainer Agent
  containers.podman.podman_container:
    name: portainer_agent
    image: portainer/agent
    restart_policy: always
    pod: podman
    volumes:
      - /tmp/podman-run-1000/podman/podman.sock:/var/run/docker.sock
      - /home/node/.local/share/containers/storage/volumes:/var/lib/docker/volumes
