version: '3'
services:
  portainer:
    image: portainer/portainer-ee:latest
    restart: always
    ports:
      - 9443:9443
    volumes:
      - /tmp/podman-run-1000/podman/podman.sock:/var/run/docker.sock
      - data:/data
